language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.8 g++-4.8 clang
  - sudo apt-get install -qq fglrx=2:8.960-0ubuntu1 opencl-headers
  - sudo apt-get install -qq cmake
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
before_script:
  - mkdir install
  - export PATH=`pwd`/install/bin:${PATH}
  - export LD_LIBRARY_PATH=`pwd`/install/lib64:`pwd`/install/lib:${LD_LIBRARY_PATH}
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=../install ..
script:
  - make
  - make install
notifications:
  email: false
